apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::432686001313:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-6EILCVSW7WRZ
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::432686001313:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-20T13:56:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "755"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b598a2c4-3b8c-11ea-817b-0e7821a88ff0
